#!/usr/bin/env python
"""Pre-release consistency check for dash-mui-charts.

Run before cutting a tag (release.yml runs it on every tag, ci.yml's package
job on every push). It catches the release-shaped mistakes no functional test
can see, because the app runs perfectly with all of them — this repo shipped
FIVE conflicting version strings at once before the network-standard pass
(package.json 1.4.0, PyPI 1.2.3, header badge v1.3.0, JSON-LD 1.2.1, README
"9 components"):

1. **Version drift across the two real sources.** setup.py reads the ROOT
   package.json — that is what PyPI serves. `dash_mui_charts.__version__`
   reads `dash_mui_charts/package-info.json`, a DIFFERENT file regenerated by
   `npm run build`. Bump the root and skip the rebuild and the wheel's label
   and its `__version__` disagree. (Every other surface — header badge,
   JSON-LD, noscript — derives from these at boot; tests/test_version_parity
   holds that side.)
2. **The committed bundle stale** relative to src/lib/components.
3. **CHANGELOG not mentioning the version being released.**
4. **Packaging drift** — the wheel picking up more than dash_mui_charts/, or
   the Dash floor in setup.py disagreeing with what CI measures.

    python scripts/check_release.py                   # check
    python scripts/check_release.py --version 1.4.0   # also assert the target

Exit code 0 when clean, 1 otherwise.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The Dash floor the PACKAGE promises. CI's package jobs measure it (a wheel
# install against dash==3.3.0 and against the current release); setup.py must
# agree, or the promise and the measurement have quietly diverged. The DOCS
# SITE floor is separate and higher — dash-improve-my-llms pins dash>=4.1 —
# and is asserted by ci.yml's docs jobs, not here.
DASH_PACKAGE_FLOOR = "3.3"

COMPONENT_COUNT = 13

problems: list[str] = []
notes: list[str] = []


def strip_html_comments(html: str) -> str:
    """`<!-- ... -->` removed, so a check cannot match its own explanation —
    templates/index.html documents the tags it must NOT contain."""
    return re.sub(r"<!--.*?-->", "", html, flags=re.S)


def check(label: str, ok: bool, detail: str = "") -> None:
    print(f"  {'PASS' if ok else 'FAIL'}  {label:<52} {detail}")
    if not ok:
        problems.append(f"{label}: {detail}")


def check_bundle_freshness(bundle: Path) -> None:
    """Is the committed JS bundle older than the React source it is built
    from? Git commit timestamps, not filesystem mtimes — git does not record
    mtimes, so a fresh clone stamps every file with checkout time and the
    comparison decays to sub-second write ordering. Equal timestamps are the
    healthy case (bundle and source committed together)."""
    def last_commit(path: str) -> int | None:
        try:
            out = subprocess.run(
                ["git", "log", "-1", "--format=%ct", "--", path],
                cwd=ROOT, capture_output=True, text=True, timeout=15,
            )
            return int(out.stdout.strip()) if out.stdout.strip() else None
        except Exception:  # noqa: BLE001 — not a git checkout, or no git
            return None

    bundle_at = last_commit(str(bundle.relative_to(ROOT)))
    src_at = last_commit("src/lib/components")

    if bundle_at is None or src_at is None:
        notes.append(
            "bundle freshness not checked — no git history here (a tarball "
            "install, or a shallow clone without the relevant commits)."
        )
        print(f"  SKIP  {'bundle newer than src/lib/components':<52} no git history")
        return

    check("bundle newer than src/lib/components", bundle_at >= src_at,
          "up to date" if bundle_at >= src_at else
          f"STALE — src committed {src_at - bundle_at}s after the bundle; "
          "run npm run build and commit the result")


def versions() -> dict[str, str]:
    out: dict[str, str] = {}
    out["package.json (setup.py reads this)"] = json.loads(
        (ROOT / "package.json").read_text()
    )["version"]
    shipped = ROOT / "dash_mui_charts" / "package-info.json"
    if shipped.exists():
        out["dash_mui_charts/package-info.json (__version__)"] = json.loads(
            shipped.read_text()
        )["version"]
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--version", help="assert every source reports this version")
    args = ap.parse_args()

    print("\ndash-mui-charts release check\n" + "=" * 68)

    print("\n[versions]")
    vs = versions()
    for name, v in vs.items():
        print(f"        {name:<52} {v}")
    unique = set(vs.values())
    check("all version sources agree", len(unique) == 1,
          "consistent" if len(unique) == 1 else f"differ: {sorted(unique)}")
    target = args.version or vs["package.json (setup.py reads this)"]
    if args.version:
        check(f"every source is {args.version}", unique == {args.version},
              "ok" if unique == {args.version} else f"found {sorted(unique)}")

    print("\n[build artifacts]")
    bundle = ROOT / "dash_mui_charts" / "dash_mui_charts.min.js"
    check("JS bundle committed", bundle.exists(),
          f"{bundle.stat().st_size // 1024} KB" if bundle.exists()
          else "MISSING — run npm run build")
    if bundle.exists():
        check_bundle_freshness(bundle)

    react = sorted(p.name.replace(".react.js", "")
                   for p in (ROOT / "src" / "lib" / "components").glob("*.react.js"))
    generated = sorted(p.stem for p in (ROOT / "dash_mui_charts").glob("*.py")
                       if p.stem in react or p.stem[:1].isupper())
    check("a Python class per React component",
          set(generated) == set(react),
          f"{len(generated)} classes"
          if set(generated) == set(react)
          else f"drift: {sorted(set(react) ^ set(generated))} — run npm run build")
    check(f"component count is {COMPONENT_COUNT}", len(react) == COMPONENT_COUNT,
          f"{len(react)} React sources")

    print("\n[changelog]")
    changelog_path = ROOT / "CHANGELOG.md"
    if changelog_path.exists():
        changelog = changelog_path.read_text()
        check(f"CHANGELOG mentions {target}", target in changelog,
              "found" if target in changelog else f"add a [{target}] section")
        if "## [Unreleased]" in changelog:
            body = changelog.split("## [Unreleased]", 1)[1].split("## [", 1)[0]
            if body.strip() and "Nothing yet" not in body:
                notes.append(
                    "CHANGELOG still has content under [Unreleased] — move it "
                    f"under [{target}] before tagging."
                )
    else:
        check("CHANGELOG.md present", False, "MISSING")

    print("\n[packaging]")
    setup_py = (ROOT / "setup.py").read_text()
    pkg_name = json.loads((ROOT / "package.json").read_text())["name"]
    check("package.json name is the import name", pkg_name == "dash_mui_charts",
          pkg_name)
    check("only the package_name is packaged",
          "packages=[package_name]" in setup_py.replace(" ", ""),
          "lib/, pages/ and assets/ stay out of the wheel")
    # Anchored to install_requires — a bare "dash>=" search would match the
    # comment explaining the two floors before it matched the requirement.
    floor = re.search(r"install_requires=\[\s*['\"]dash>=([\d.]+)['\"]", setup_py)
    check(f"setup.py Dash floor is {DASH_PACKAGE_FLOOR}",
          floor is not None and floor.group(1).startswith(DASH_PACKAGE_FLOOR),
          f"dash>={floor.group(1)}" if floor else "no dash requirement found")
    check("dash is the only hard runtime dependency",
          re.search(r"install_requires=\[\s*'dash>=[\d.]+',?\s*\]", setup_py)
          is not None
          or re.search(r'install_requires=\[\s*"dash>=[\d.]+",?\s*\]', setup_py)
          is not None,
          "site deps live in requirements.txt")
    check("LICENSE present", (ROOT / "LICENSE").exists())
    check("README present", (ROOT / "README.md").exists())
    check("MANIFEST.in present", (ROOT / "MANIFEST.in").exists())
    manifest = (ROOT / "MANIFEST.in").read_text()
    check("MANIFEST ships the version source",
          "include package.json" in manifest,
          "setup.py reads package.json — an sdist without it cannot build")

    print("\n[seo]")
    # templates/index.html cannot import lib/constants (it is a static file),
    # so its origin and version are TOKENS substituted at boot. A literal
    # origin or version left in the template is the exact drift Phase 1
    # removed — five conflicting version strings, og tags pinned to
    # onrender.com.
    tpl = (ROOT / "templates" / "index.html").read_text()
    base = re.search(
        r'^DEFAULT_BASE_URL\s*=\s*"([^"]+)"',
        (ROOT / "lib" / "constants.py").read_text(), re.M,
    ).group(1).rstrip("/")
    check("template takes its origin from constants.py",
          "__CANONICAL_ORIGIN__" in tpl,
          f"{tpl.count('__CANONICAL_ORIGIN__')} tokens → {base}")
    check("template takes its version from the package",
          "__APP_VERSION__" in tpl,
          f"{tpl.count('__APP_VERSION__')} tokens")
    tpl_markup = strip_html_comments(tpl)
    hard_coded = sorted(set(re.findall(
        r"https://[a-z0-9.-]*(?:onrender\.com|2plot\.dev)", tpl_markup)))
    check("no hard-coded origin left in the template", not hard_coded,
          "all tokenised" if not hard_coded else "found: " + ", ".join(hard_coded))
    # dash-improve-my-llms >= 2.3.3 prerenders <link rel="canonical"> per
    # route; a literal tag in the template would be a SECOND canonical on
    # every page, and two canonicals is worse than none. The `<` is what
    # distinguishes a real tag from the querySelector string the client-side
    # sync script legitimately contains.
    check("template hard-codes no canonical",
          '<link rel="canonical"' not in tpl_markup,
          "the package prerenders it per route")
    head = tpl.split("</head>")[0]
    restated = [t for t in ('name="description"', 'property="og:title"',
                            'property="og:description"', 'property="og:type"',
                            'name="twitter:card"', 'name="twitter:title"',
                            'name="twitter:description"')
                if t in strip_html_comments(head)]
    check("template does not restate per-page meta tags", not restated,
          "only site-level tags" if not restated
          else "duplicates Dash: " + ", ".join(restated))

    print("\n[network]")
    reqs = (ROOT / "requirements.txt").read_text()
    floor = re.search(r"dash-improve-my-llms>=([\d.]+)", reqs)
    ok_floor = floor is not None and tuple(
        int(x) for x in floor.group(1).split(".")
    ) >= (2, 3, 4)
    check("dash-improve-my-llms floor >= 2.3.4", ok_floor,
          f">={floor.group(1)}" if floor else "not pinned in requirements.txt")
    # Anchored to line start: the requirements COMMENT quotes markdown2dash's
    # spurious `gunicorn>=21.2.0,<22` pin, which a bare search matches first.
    gunicorn_floor = re.search(r"^gunicorn>=([\d.]+)", reqs, re.M)
    check("gunicorn floor >= 23 (CVE-2024-6827/-1135)",
          gunicorn_floor is not None
          and int(gunicorn_floor.group(1).split(".")[0]) >= 23,
          f">={gunicorn_floor.group(1)}" if gunicorn_floor else "not pinned")
    for mod in ("constants", "analytics", "traffic_report", "ad_client",
                "bulletin", "network_directory"):
        check(f"lib/{mod}.py present", (ROOT / "lib" / f"{mod}.py").exists())

    render_yaml = (ROOT / "render.yaml").read_text()
    host = base.split("://", 1)[-1]
    if f"- {host}" in render_yaml:
        check("render.yaml serves the canonical host", True, f"domains: {host}")
    else:
        # Phase 4 of the network-standard pass attaches the domain; until
        # then this is informational, not a failed release.
        notes.append(
            f"render.yaml declares no `domains: [{host}]` yet — expected "
            "until the Phase 4 cutover attaches the subdomain."
        )
        print(f"  NOTE  {'render.yaml serves the canonical host':<52} pending Phase 4")

    print("\n[docs site]")
    for f in ("Dockerfile", "render.yaml", "requirements.txt", "run.py",
              "scripts/route_parity.py", "scripts/network_smoke.py",
              "scripts/smoke_live.py"):
        check(f"{f} present", (ROOT / f).exists())
    check("requirements use no absolute paths", "file:///" not in reqs,
          "no absolute file:// URLs")

    print("\n[ci]")
    for wf in ("ci.yml", "cd.yml", "release.yml"):
        check(f".github/workflows/{wf}", (ROOT / ".github" / "workflows" / wf).exists())

    print("\n" + "=" * 68)
    for n in notes:
        print(f"NOTE: {n}")
    if problems:
        print(f"\n{len(problems)} problem(s) — not ready to tag:")
        for p in problems:
            print(f"  - {p}")
        return 1
    print(f"\nClean. Ready to tag v{target} "
          "(release.yml publishes on the tag push via PyPI trusted publishing).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
